// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file proto/v1/config.proto (package proto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type {
  EnvironmentVariable,
  JobMeta,
  WorkflowMeta,
} from "./shared_pb.ts";
import { file_proto_v1_shared } from "./shared_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/v1/config.proto.
 */
export const file_proto_v1_config: GenFile = /*@__PURE__*/
  fileDesc(
    "ChVwcm90by92MS9jb25maWcucHJvdG8SCHByb3RvLnYxIoECChhXb3JrZmxvd1J1bm5lckluaXRDb25maWcSLQoNd29ya2Zsb3dfbWV0YRgBIAEoCzIWLnByb3RvLnYxLldvcmtmbG93TWV0YRIcChRvcmNoZXN0cmF0b3JfYWRkcmVzcxgCIAEoCRIMCgRmaWxlGAMgASgJEhYKDnB1YmxpY19qd3Rfa2V5GAQgASgJEhwKFHByZXNpZ25lZF9vdXRwdXRfdXJsGAUgASgJEgwKBGhvc3QYBiABKAkSEQoEcG9ydBgHIAEoBUgAiAEBEioKA2VudhgIIAMoCzIdLnByb3RvLnYxLkVudmlyb25tZW50VmFyaWFibGVCBwoFX3BvcnQi4QEKE0pvYlJ1bm5lckluaXRDb25maWcSLQoNd29ya2Zsb3dfbWV0YRgBIAEoCzIWLnByb3RvLnYxLldvcmtmbG93TWV0YRIjCghqb2JfbWV0YRgCIAEoCzIRLnByb3RvLnYxLkpvYk1ldGESHAoUb3JjaGVzdHJhdG9yX2FkZHJlc3MYAyABKAkSFgoOcnVubmVyX2FkZHJlc3MYBCABKAkSFgoOcHVibGljX2p3dF9rZXkYBSABKAkSDAoEaG9zdBgGIAEoCRIRCgRwb3J0GAcgASgFSACIAQFCBwoFX3BvcnRCDVoLcHJvdG8vZ28vdjFiBnByb3RvMw",
    [file_proto_v1_shared],
  );

/**
 * @generated from message proto.v1.WorkflowRunnerInitConfig
 */
export type WorkflowRunnerInitConfig =
  & Message<"proto.v1.WorkflowRunnerInitConfig">
  & {
    /**
     * @generated from field: proto.v1.WorkflowMeta workflow_meta = 1;
     */
    workflowMeta?: WorkflowMeta;

    /**
     * @generated from field: string orchestrator_address = 2;
     */
    orchestratorAddress: string;

    /**
     * @generated from field: string file = 3;
     */
    file: string;

    /**
     * @generated from field: string public_jwt_key = 4;
     */
    publicJwtKey: string;

    /**
     * @generated from field: string presigned_output_url = 5;
     */
    presignedOutputUrl: string;

    /**
     * @generated from field: string host = 6;
     */
    host: string;

    /**
     * @generated from field: optional int32 port = 7;
     */
    port?: number;

    /**
     * @generated from field: repeated proto.v1.EnvironmentVariable env = 8;
     */
    env: EnvironmentVariable[];
  };

/**
 * Describes the message proto.v1.WorkflowRunnerInitConfig.
 * Use `create(WorkflowRunnerInitConfigSchema)` to create a new message.
 */
export const WorkflowRunnerInitConfigSchema: GenMessage<
  WorkflowRunnerInitConfig
> = /*@__PURE__*/
  messageDesc(file_proto_v1_config, 0);

/**
 * @generated from message proto.v1.JobRunnerInitConfig
 */
export type JobRunnerInitConfig = Message<"proto.v1.JobRunnerInitConfig"> & {
  /**
   * @generated from field: proto.v1.WorkflowMeta workflow_meta = 1;
   */
  workflowMeta?: WorkflowMeta;

  /**
   * @generated from field: proto.v1.JobMeta job_meta = 2;
   */
  jobMeta?: JobMeta;

  /**
   * @generated from field: string orchestrator_address = 3;
   */
  orchestratorAddress: string;

  /**
   * @generated from field: string runner_address = 4;
   */
  runnerAddress: string;

  /**
   * @generated from field: string public_jwt_key = 5;
   */
  publicJwtKey: string;

  /**
   * @generated from field: string host = 6;
   */
  host: string;

  /**
   * @generated from field: optional int32 port = 7;
   */
  port?: number;
};

/**
 * Describes the message proto.v1.JobRunnerInitConfig.
 * Use `create(JobRunnerInitConfigSchema)` to create a new message.
 */
export const JobRunnerInitConfigSchema: GenMessage<
  JobRunnerInitConfig
> = /*@__PURE__*/
  messageDesc(file_proto_v1_config, 1);
