-- Create enum type "step_type_enum"
CREATE TYPE "step_type_enum" AS ENUM ('exec');
-- Create enum type "user_account_type_enum"
CREATE TYPE "user_account_type_enum" AS ENUM ('github');
-- Create "user_account" table
CREATE TABLE "user_account" ("user_id" uuid NOT NULL, "type" "user_account_type_enum" NOT NULL, "provider_account_id" character(36) NOT NULL, "refresh_token" character varying(255) NOT NULL, "refresh_token_expires_at" timestamp NOT NULL, "access_token" character varying(255) NOT NULL, "access_token_expires_at" timestamp NOT NULL, PRIMARY KEY ("user_id", "type"), CONSTRAINT "user_account_type_provider_account_id_key" UNIQUE ("type", "provider_account_id"));
-- Create enum type "git_integration_type_enum"
CREATE TYPE "git_integration_type_enum" AS ENUM ('github');
-- Create enum type "run_status_enum"
CREATE TYPE "run_status_enum" AS ENUM ('queued', 'running', 'completed', 'pending');
-- Create enum type "run_conclusion_enum"
CREATE TYPE "run_conclusion_enum" AS ENUM ('success', 'failure', 'cancelled', 'skipped');
-- Create enum type "run_trigger_enum"
CREATE TYPE "run_trigger_enum" AS ENUM ('push', 'pull_request-opened', 'pull_request-synchronize', 'pull_request-closed', 'manual');
-- Create enum type "org_role_enum"
CREATE TYPE "org_role_enum" AS ENUM ('admin', 'member');
-- Create "git_integration" table
CREATE TABLE "git_integration" ("id" character(21) NOT NULL, "provider_id" character varying(36) NOT NULL, "provider_account_id" character varying(36) NOT NULL, "type" "git_integration_type_enum" NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "git_integration_provider_account_id_type_provider_id_key" UNIQUE ("provider_account_id", "type", "provider_id"), CONSTRAINT "git_integration_provider_id_type_key" UNIQUE ("provider_id", "type"));
-- Create "user_account_oauth_state" table
CREATE TABLE "user_account_oauth_state" ("id" character(21) NOT NULL, "user_id" uuid NOT NULL, "type" "user_account_type_enum" NOT NULL, "created_at" timestamp NOT NULL, PRIMARY KEY ("id"));
-- Create "org" table
CREATE TABLE "org" ("id" character(21) NOT NULL, "slug" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "avatar_url" character varying(255) NOT NULL, "license" jsonb NULL, "owner_user_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "org_slug_key" UNIQUE ("slug"));
-- Create "project" table
CREATE TABLE "project" ("id" character(21) NOT NULL, "org_id" character(21) NOT NULL, "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "avatar_url" character varying(255) NULL, "git_integration_id" character(21) NOT NULL, "git_provider_repo_id" character varying(36) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "project_org_id_slug_key" UNIQUE ("org_id", "slug"), CONSTRAINT "project_git_integration_id_fkey" FOREIGN KEY ("git_integration_id") REFERENCES "git_integration" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "project_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "org" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "workflow_run" table
CREATE TABLE "workflow_run" ("id" character(21) NOT NULL, "number" integer NOT NULL, "created_at" timestamp NOT NULL, "finished_at" timestamp NULL, "project_id" character(21) NOT NULL, "status" "run_status_enum" NOT NULL, "conclusion" "run_conclusion_enum" NULL, "name" character varying(255) NOT NULL, "git_title" character varying(255) NULL, "runner" character varying(255) NOT NULL DEFAULT 'ubuntu-2x', "git_sha" text NOT NULL, "git_branch" text NOT NULL, "committer_email" text NULL, "user_id" uuid NULL, "pr_number" integer NULL, "build_minutes" integer NOT NULL DEFAULT 0, "trigger" "run_trigger_enum" NOT NULL DEFAULT 'push', "alerts" jsonb NULL DEFAULT '[]', PRIMARY KEY ("id"), CONSTRAINT "workflow_run_project_id_number_key" UNIQUE ("project_id", "number"), CONSTRAINT "workflow_run_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "job_run" table
CREATE TABLE "job_run" ("id" character(21) NOT NULL, "number" integer NOT NULL, "created_at" timestamp NOT NULL, "finished_at" timestamp NULL, "workflow_run_id" character(21) NOT NULL, "status" "run_status_enum" NOT NULL, "build_minutes" integer NOT NULL DEFAULT 0, "conclusion" "run_conclusion_enum" NULL, "name" character varying(255) NOT NULL, "runner" character varying(255) NOT NULL DEFAULT 'ubuntu-4x', PRIMARY KEY ("id"), CONSTRAINT "job_run_workflow_run_id_number_key" UNIQUE ("workflow_run_id", "number"), CONSTRAINT "job_run_workflow_run_id_fkey" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_run" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "org_users" table
CREATE TABLE "org_users" ("user_id" uuid NOT NULL, "org_id" character(21) NOT NULL, "role" "org_role_enum" NOT NULL, PRIMARY KEY ("user_id", "org_id"), CONSTRAINT "org_users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "org" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "pending_org_invites" table
CREATE TABLE "pending_org_invites" ("org_id" character(21) NOT NULL, "email" character varying(255) NOT NULL, "role" "org_role_enum" NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("org_id", "email"), CONSTRAINT "pending_org_invites_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "org" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "project_environment" table
CREATE TABLE "project_environment" ("id" character(21) NOT NULL, "project_id" character(21) NOT NULL, "name" character varying(255) NOT NULL, "branch_pattern" character varying(255) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "project_environment_project_id_name_key" UNIQUE ("project_id", "name"), CONSTRAINT "project_environment_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "project_variable" table
CREATE TABLE "project_variable" ("id" character(21) NOT NULL, "project_id" character(21) NOT NULL, "key" character varying(255) NOT NULL, "value" text NOT NULL, "encryption_key_id" character(8) NOT NULL, "initialisation_vector" text NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "sensitive" boolean NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "project_variable_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "project_variable_on_project_environment" table
CREATE TABLE "project_variable_on_project_environment" ("project_environment_id" character(21) NOT NULL, "project_variable_id" character(21) NOT NULL, PRIMARY KEY ("project_environment_id", "project_variable_id"), CONSTRAINT "project_variable_on_project_environ_project_environment_id_fkey" FOREIGN KEY ("project_environment_id") REFERENCES "project_environment" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "project_variable_on_project_environmen_project_variable_id_fkey" FOREIGN KEY ("project_variable_id") REFERENCES "project_variable" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "task_run" table
CREATE TABLE "task_run" ("id" character(21) NOT NULL, "workflow_run_id" character(21) NOT NULL, "created_at" timestamp NOT NULL, "finished_at" timestamp NULL, "job_run_id" character(21) NOT NULL, "name" character varying(255) NOT NULL, "status" "run_status_enum" NOT NULL, "conclusion" "run_conclusion_enum" NULL, "docker_image" character varying(255) NULL, "meta" jsonb NULL, PRIMARY KEY ("id"), CONSTRAINT "task_run_job_run_id_fkey" FOREIGN KEY ("job_run_id") REFERENCES "job_run" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "task_run_workflow_run_id_fkey" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_run" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "step_run" table
CREATE TABLE "step_run" ("id" character(21) NOT NULL, "workflow_run_id" character(21) NOT NULL, "type" "step_type_enum" NOT NULL, "created_at" timestamp NOT NULL, "finished_at" timestamp NULL, "task_run_id" character(21) NOT NULL, "job_run_id" character(21) NOT NULL, "status" "run_status_enum" NOT NULL, "conclusion" "run_conclusion_enum" NULL, "name" character varying(255) NOT NULL, "meta" jsonb NULL, PRIMARY KEY ("id"), CONSTRAINT "step_run_job_run_id_fkey" FOREIGN KEY ("job_run_id") REFERENCES "job_run" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "step_run_task_run_id_fkey" FOREIGN KEY ("task_run_id") REFERENCES "task_run" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "step_run_workflow_run_id_fkey" FOREIGN KEY ("workflow_run_id") REFERENCES "workflow_run" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
